### ISSUE TITLE
LV-PUR131S

### ISSUE THREAD

**Issue by rzolau** [webdjoe/pyvesync#31]
I did quick check on LV-PUR131S API. Here are some comments:

- in `vesyncfan::get_details()` there is typo in URL. Currently, it is `/131airpurifier/v1/device/deviceDetail` and it should be `/131airPurifier/v1/device/deviceDetail` (notice capitalized P).
- when URL is fixed, the returned json is: `{'code': 4001001, 'msg': '参数为空', 'deviceStatus': None, 'connectionStatus': None, 'activeTime': None, 'deviceImg': None, 'deviceName': None, 'filterLife': None, 'airQuality': None, 'screenStatus': None, 'mode': None, 'level': None, 'schedule': None, 'timer': None, 'scheduleCount': None}` I think this is because device's `uuid` is missing in the post body

参数为空 apparently meaning "The parameter is empty"

**Comment by webdjoe** [comment]
Thanks for catching that, just pushed a fix

**Comment by webdjoe** [comment]
@rzolau I updated the code on the latest PR https://github.com/markperdue/pyvesync/pull/30.  If you wouldn't mind checking to see if the rest of the functionality is working for air purifiers.

**Comment by markperdue** [comment]
Thanks @webdjoe for following up on this.

**Comment by rzolau** [comment]
I am doing some small testing from time to time (time permitting). Here is another issue: in line 124 (method `mode_toggle`) `body` should not be referenced for `mode`, the intention I think was to test `self.details['mode']`.

Apologies for dragging this issue instead of doing proper PR - but I am doing tests in super ad-hoc manner :-)

**Comment by webdjoe** [comment]
No worries, I greatly appreciate the feedback.  Line 124 is referring to the `change_fan_speed` method in my editor. I changed it so that it will only change the fan speed if the mode is manual.  The `self.details['mode']` was changed to `self.mode`, since it is set when the device object is instantiated.  I made a new branch [airpur-bug](https://github.com/markperdue/pyvesync/tree/airpure-bug) if you wouldn't mind downloading the branch and testing it out.

**Comment by metril** [comment]
Hey guys. Great library here and glad that you're integrating with Home Assistant. I too have the LV-PUR131S. Right now, it's not at all detected in Home Assistant. In fact, it looks like the module fails to load in HA and it looks like it's erroring on all the "fan" related functions.

**Comment by webdjoe** [comment]
Hi @metril, thank you for taking the time to post this issue.  We are currently working on integrating with HA, so there is currently no support for the LV-PUR131S in the custom component.  I took the liberty of open a new issue [LV-PUR131S Home Assistant Integration #33](https://github.com/markperdue/pyvesync/issues/33) with your post so that we can specifically track HA integration issues.  Please check back soon, there should be a new custom component out in hopefully a few days.

**Comment by rzolau** [comment]
Finally did quite extensive testing on the airpur-bug branch. The only issue I found so far is in `mode_toggle` method. mode in `body` is not set. Adding `body['mode'] = mode` just before the call to `helpers.call_api` solves the problem.

**Comment by webdjoe** [comment]
Thanks for the feedback @rzolau.  That will be fixed in the next PR.

**Comment by webdjoe** [comment]
Fixed with https://github.com/markperdue/pyvesync/pull/34/files
