### ISSUE TITLE
Support for Levoit Core 200S Air Purifier

### ISSUE THREAD

**Issue by synergicmind** [webdjoe/pyvesync#68]
Hello,

Would you be able to add support for Levoit Core 200S Smart True HEPA Air Purifier please? I just purchased the unit solely to use with HA. So please let me know anyway I could help.
Thanks.

**Comment by SandroGrzicic** [comment]
Presumably the 200S has a similar VeSync interface as the 300S, however it's always a good idea to do packet capture and submit your captures here so that the devs can add proper support, see a previous issue with more details: https://github.com/webdjoe/pyvesync/issues/41

I was unable to use the linked app on my Android 10 phone, however I managed to run it on an older device running Android 8 which is how I did the packet captures for my 300S.

**Comment by synergicmind** [comment]
What app do you use in Android device to capture packet?

**Comment by jlboygenius** [comment]
I've used Packet Capture (blue circle with a yellow arrow logo). It acts as a VPN and does a main in the middle attack, so you can see all the traffic sent by your apps. Pretty neat, and will make you want to uninstall a lot of apps when you see how much data they are sending.

**Comment by webdjoe** [comment]
Just merged with 1.4.0. Haven't test myself, so let me know if there are any issues.
